spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: admin
    password: root@root

  jackson:
    default-property-inclusion: non_null

jwt:
  secret: d9b2e2bf-3a04-4198-b7e8-b71d9c0b4b7f
  expiration: 999999